### ISSUE TITLE
metro ui 4

### ISSUE THREAD

**Issue by alri** [troxler/awesome-css-frameworks#43] opened 2020-02-16 07:28 UTC
hi .
why metro ui 4 is not in your list or other people list ?

**Comment by troxler** [comment] 2020-02-16 10:45
There is already PR #30 for that. However, Metro 4 seems severely lacking in regards of keyboard support. I created a [bug report](https://github.com/olton/Metro-UI-CSS/issues/1366) which was then closed by the author. I do not see any way to properly track the progress and a quick test showed that Metro 4 still has no (or bad) support for keyboard navigation.

Duplicate of #30.

**Closed by troxler** 2020-02-16 10:45 UTC
