### ISSUE TITLE
Frameworks dependent on Tailwind and Bootstrap

### ISSUE THREAD

**Issue by Laisvunas** [troxler/awesome-css-frameworks#96] opened 2022-05-19 12:23 UTC
There are frameworks dependent on Tailwind and Bootstrap, which might be added to the list:

https://daisyui.com/

https://mdbootstrap.com/

**Comment by troxler** [comment] 2022-05-21 10:27
Duplicate of #79 and #45/#77.

**Closed by troxler** 2022-05-21 10:27 UTC
