### ISSUE TITLE
Stylify CSS

### ISSUE THREAD

**Issue by Machy8** [troxler/awesome-css-frameworks#107] opened 2022-12-02 19:18 UTC
Hi, please, could you add Stylify CSS? #108

**Comment by troxler** [comment] 2022-12-11 12:43
Duplicate of #108.

**Closed by troxler** 2022-12-11 12:43 UTC

**Comment by Machy8** [comment] 2022-12-11 19:16
Hi. Sorry about that. I created an issue before the pull. Then I realized that the issue template you have is probably for the pull request so I created a pull request and linked it with this issue.

**Comment by troxler** [comment] 2022-12-11 19:18
No worries :) I just did some cleaning up.
